apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ssc-cxp-demo-pot-autoscaler
  namespace: cxp-team-heiterbiswolkig
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ssc-cxp-demo-deployment
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80
