kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster-with-port-mapping-and-nodeport-service
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30950
        hostPort: 80